[package]
name = "canzero-udp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canzero-config = { git = "https://github.com/mu-zero-HYPERLOOP/canzero-config.git" }
serde = { version = "1.0.197", features = ["derive", "serde_derive"] }
tokio = { version = "1.36.0", features = ["full"] }
bincode = { version = "1.3.3", features = ["i128"] }
color-print = "0.3.6"
chrono = "0.4.38"
build-time = "0.1.3"
